FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

RUN chmod +x start.sh

# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "simba:application"]
CMD ["./start.sh"]